app:
  db:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: 0
    ddl-auto: create-drop
    driver: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8082
